"""Finalise imagery: swap in the strongest hero, crop a distraction out of one card,
and rebuild the blur-placeholder map from the images actually on disk."""
import base64
import glob
import io
import json
import os
import urllib.request

from PIL import Image, ImageDraw

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
IMG_ROOT = os.path.join(ROOT, "public", "images")
SHEET = os.path.join(os.environ.get("TEMP", "/tmp"), "gg_sheets")
UA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"}


def pull(pid, width):
    url = f"https://images.unsplash.com/photo-{pid}?w={width}&q=80&fm=jpg&fit=max&auto=format"
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=90) as r:
        return r.read()


def main():
    # 1. Hero: the white-and-timber desert villa, wide and cinematic.
    hero = os.path.join(IMG_ROOT, "site", "hero-estate.jpg")
    with open(hero, "wb") as f:
        f.write(pull("1613490493576-7fde63acd811", 2560))
    print("hero ->", hero, os.path.getsize(hero) // 1024, "KB")

    # 2. Paradise Valley card: crop the construction crane out of the right edge.
    card = os.path.join(IMG_ROOT, "properties", "paradise-valley-modern-desert-estate.jpg")
    with open(card, "wb") as f:
        f.write(pull("1600596542815-ffad4c1539a9", 1800))
    im = Image.open(card)
    w, h = im.size
    im.crop((0, 0, int(w * 0.72), h)).save(card, quality=86)
    print("card cropped ->", Image.open(card).size)

    # 3. Drop the now-unused hero candidate.
    stale = os.path.join(IMG_ROOT, "site", "hero-desert-villa.jpg")
    if os.path.exists(stale):
        os.remove(stale)
        print("removed stale hero")

    # 4. Rebuild blur map from what is actually on disk.
    blur = {}
    for path in sorted(glob.glob(os.path.join(IMG_ROOT, "**", "*.jpg"), recursive=True)):
        rel = "/" + os.path.relpath(path, os.path.join(ROOT, "public")).replace("\\", "/")
        img = Image.open(path).convert("RGB")
        tw = 16
        th = max(1, round(tw * img.size[1] / img.size[0]))
        buf = io.BytesIO()
        img.resize((tw, th), Image.LANCZOS).save(buf, format="JPEG", quality=42)
        blur[rel] = "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()

    lines = [
        "// AUTO-GENERATED by .workbuddy-ai/tools/finalise_images.py — do not edit by hand.",
        '// Tiny base64 LQIP placeholders used with next/image `placeholder="blur"`.',
        "",
        "export const blurData: Record<string, string> = {",
    ]
    for k in sorted(blur):
        lines.append(f'  "{k}":')
        lines.append(f'    "{blur[k]}",')
    lines += [
        "};",
        "",
        "/** LQIP placeholder for a public image path, if one was generated. */",
        "export function blurFor(src: string): string | undefined {",
        "  return blurData[src];",
        "}",
        "",
    ]
    out = os.path.join(ROOT, "src", "lib", "blur-data.ts")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("blur map:", len(blur), "entries")

    # 5. Contact sheet of the final local set, for a last visual check.
    files = sorted(glob.glob(os.path.join(IMG_ROOT, "**", "*.jpg"), recursive=True))
    cols, cw, ch = 6, 260, 190
    rows = (len(files) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * cw, rows * (ch + 20)), (247, 244, 238))
    draw = ImageDraw.Draw(sheet)
    for i, p in enumerate(files):
        r, c = divmod(i, cols)
        try:
            t = Image.open(p).convert("RGB").resize((cw, ch))
        except Exception:  # noqa: BLE001
            continue
        x, y = c * cw, r * (ch + 20)
        sheet.paste(t, (x, y))
        label = f"{os.path.basename(os.path.dirname(p))}/{os.path.basename(p)[:26]}"
        draw.text((x + 4, y + ch + 4), label, fill=(25, 25, 25))
    os.makedirs(SHEET, exist_ok=True)
    dest = os.path.join(SHEET, "final.jpg")
    sheet.save(dest, quality=80)
    print("FINAL SHEET", dest, sheet.size)

    with open(os.path.join(ROOT, ".workbuddy-ai", "image-manifest.json"), "w", encoding="utf-8") as f:
        json.dump([os.path.relpath(p, ROOT).replace("\\", "/") for p in files], f, indent=2)


if __name__ == "__main__":
    main()
